### ISSUE TITLE
Trying to install on mac

### ISSUE THREAD

**Issue by jmcarter17** [xkbeyer/cdt-catch#1]
Tried to install manually.
I have Java 1.8.0_66
Eclipse Mars 4.5.2
CDT 8.8.1

I put the jar file in the dropins folder, then did a clean mode start of eclipse, but the runner is not selectable. Any ideas?

Also, do you know when you will have an updated version that work with Sections?

**Comment by jmcarter17** [comment]
My mistake, 

the first time I downloaded the file, it got corrupted (don't know why)
It's working now, with a non-corrupted jar file.

If you can now support SECTIONS, I would be really happy.

**Comment by xkbeyer** [comment]
Great to hear that it works.
Regarding sections: Actually I don't have a concrete plan to implement that, because I don't use it till now.
However, I'll look into it in the next days.

**Comment by jmcarter17** [comment]
Awesome, I'll look forward to test it if you want.
I use SECTIONS a LOT.

**Comment by xkbeyer** [comment]
Ok, done. Please give it a try.

**Comment by jmcarter17** [comment]
Tried it with a few sections.
So far so good.
Thanks man this is fantastic!
