### ISSUE TITLE
Test runner fails with Element type "testsuitesApr" must be followed by either attribute specifications, ">" or "/>".

### ISSUE THREAD

**Issue by vvvlc** [xkbeyer/cdt-catch#3]
Hi 
Test runner fails with error message  
```
Element type "testsuitesApr" must be followed by either attribute specifications, ">" or "/>".
```
here is [log.txt](https://github.com/xkbeyer/cdt-catch/files/1873095/log.txt) generated by my catch2 test program `/arduino-wattercounting-catch --success --reporter xml --durations yes > log.txt`  , that fails.

I assume that problem appears when program prints something on stdout via `printf()`.
```xml
...
      <Section name="setup" filename="../test/watterpulsecounting-integration-test.cpp" line="32">
Apr  3 2018 21:24:42 vx
S/V;finished_state;IRQ_Cnt;laps_time;pulse_duration
        <Expression success="true" type="CHECK" filename="../test/watterpulsecounting-integration-test.cpp" line="41">
          <Original>
...
```

When I disable printf in tests then test runner works fine. [log without printf - works fine](https://github.com/xkbeyer/cdt-catch/files/1873109/log-noprintf.txt)
```xml
...
      <Section name="setup" filename="../test/watterpulsecounting-integration-test.cpp" line="32">
        <Expression success="true" type="CHECK" filename="../test/watterpulsecounting-integration-test.cpp" line="41">
          <Original>
...
```

Thx for help.
Vitek

**Comment by vvvlc** [comment]
When running `./arduino-wattercounting-catch -o xxx -r xml`, xxx file has same content as [log without printf - works fine](https://github.com/xkbeyer/cdt-catch/files/1873109/log-noprintf.txt)

It looks a new parameter '-o tmpfile.randomnumber' needs to be introduced in
(https://github.com/xkbeyer/cdt-catch/blob/c4fe2e6eb66db15448a716cc853ae042b10f26be/src/org/eclipse/cdt/testsrunner/internal/catch_test/CatchTestsRunnerProvider.java#L42)

**Comment by xkbeyer** [comment]
Thanks for the report.
CDT-catch uses the Junit Reporter, would it be possible to run the test program with that reporter? 
`/arduino-wattercounting-catch --success --reporter junit --durations yes > log.txt`
Or a reduced example might be even better.
 
Since the parameter `-o` is the redirection of the output into a file, the connection is not yet clear to me.

**Comment by xkbeyer** [comment]
Ok I see what happens. Catch produces a faulty XML string with a printf command in a test case, like:
`<testsuitesTest uses a printf>`
If you use the iostream, it works fine.
`<system-out>
Test uses a printf
</system-out>
`
And the connection with the parameter -o is also clear to me. In this case, the printf string is not written to the file.
In my opinion, this is an issue for Catch. 

However, I'll look for a way to process the output anyway.

Created an issue https://github.com/catchorg/Catch2/issues/1243
