### ISSUE TITLE
Better organisation of output (Per File and Per TEST_CASE)

### ISSUE THREAD

**Issue by jmcarter17** [xkbeyer/cdt-catch#5]
I seem to remember in the past with this plugin that the output was organized in a tree form by Test File, and when SECTION was implemented, the output was also organized per TEST_CASE within a File, with SECTION being in a sub-tree of a TEST_CASE, and TEST_CASE in a sub-tree of a file (and subSECTION in a sub-tree of a SECTION)... Can we bring this feature back?

**Comment by xkbeyer** [comment]
I need to check this out. I don't remember exactly what it looked like back then.

**Comment by jmcarter17** [comment]
I may also remember wrong, but I'd still like to see a tree-like structure of the output.

**Comment by xkbeyer** [comment]
At the moment I see no possibility to realize this. To my understanding it is not possible to generate nested test cases. If I again enter a test case in a test case I get an exception and without this it does not seem possible to build a hierarchy which is displayed as a tree.

**Comment by jmcarter17** [comment]
Not a TEST_CASE in a TEST_CASE, but SECTION and nested SECTION.

**Comment by xkbeyer** [comment]
The point is, the TestModel (Eclipse) has only test cases. SECTION is treated as a test case since it has an outcome. In that context no nested test cases or SECTION are possible.
